export const AUTH_LOGGED_IN = '[AUTH] LOGGED_IN';
export const AUTH_LOGOUT = '[AUTH] LOGOUT';
export const AUTH_SET_PROFILE = '[AUTH] SET_PROFILE';

export const AUTH_ERROR_MESSAGE = '[AUTH] ERROR_LOG_IN';
export const AUTH_CLEAR_ERROR_MESSAGE = '[AUTH] CLEAR_ERROR_MESSAGE';